# SPDX-License-Identifier: GPL-2.+

#UBOOTINCLUDE += -I/home/yyy/work/tools/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/libc/usr/include
#CFLAGS += -I/home/yyy/work/tools/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/libc/usr/include
#ccflags-y = -I/home/yyy/work/tools/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/libc/usr/include
#cpp_flags +=-I/home/yyy/work/tools/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/libc/usr/include
#c_flags := $(KBUILD_CFLAGS) $(cpp_flags)


obj-y += w1_gpio.o
obj-y += w1_ds28e1x.o
obj-y += w1_ds28e1x_sha256.o
obj-y += aes_cbc.o
obj-y += aes_core.o
obj-y += cbc128.o
obj-y += hobot_aes.o
obj-y += w1_io.o
obj-y += x1_gpio.o
