# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2013 Samsung Electronics Co., Ltd.
# 	http://www.samsung.com
obj-$(CONFIG_HBOT_SECURE_ENGINE) += hb_pka.o
obj-$(CONFIG_HBOT_SECURE_ENGINE) += hb_pka_test.o
obj-$(CONFIG_HBOT_SECURE_ENGINE) += hb_spacc.o
obj-$(CONFIG_HBOT_SECURE_ENGINE) += hb_spacc_test.o
