#
# (C) Copyright 2014 - 2015 Xilinx, Inc.
# Michal Simek <michal.simek@xilinx.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_SPL_BUILD) += spl.o hb_utils.o \
			dw_mmc_spl.o \
			hb_mmc_spl.o \
			hb_ap_spl.o \
			hb_ymodem_spl.o \
			hb_nor_spl.o \
			hb_spi_spl.o \
			hb_nand_spl.o

obj-y += reset.o
