#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

# BIFSD
obj-$(CONFIG_HB_BIFSD)			+= hb_bifsd.o
obj-$(CONFIG_HB_BIFSD)			+= hb_bifsd_isr.o
