/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "hb_vin_rpc.h"

bool_t
xdr_hb_vin_bypass_arg (XDR *xdrs, hb_vin_bypass_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->port))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->enable))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hb_vin_cfg_arg (XDR *xdrs, hb_vin_cfg_arg *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_string (xdrs, &objp->filename, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->fps))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->resolution))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->entry_num))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->fps);
		IXDR_PUT_LONG(buf, objp->resolution);
		IXDR_PUT_LONG(buf, objp->entry_num);
		}
		 if (!xdr_string (xdrs, &objp->filecont, ~0))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_string (xdrs, &objp->filename, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->fps))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->resolution))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->entry_num))
				 return FALSE;

		} else {
		objp->fps = IXDR_GET_LONG(buf);
		objp->resolution = IXDR_GET_LONG(buf);
		objp->entry_num = IXDR_GET_LONG(buf);
		}
		 if (!xdr_string (xdrs, &objp->filecont, ~0))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_string (xdrs, &objp->filename, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->fps))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->resolution))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->entry_num))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->filecont, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hb_vin_snrclk_arg (XDR *xdrs, hb_vin_snrclk_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->entry))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hb_vin_pre_arg (XDR *xdrs, hb_vin_pre_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->entry))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}
